--------------------------------------------------------
--  DDL for Table DBVI_D_BEDRIJVEN_ACTUEEL
--------------------------------------------------------

  CREATE TABLE "VWASAS"."DBVI_D_BEDRIJVEN_ACTUEEL" 
   (	"AID_NUMMER_PRIMAIR" NUMBER, 
	"SAP_NUMMER_BEHEERDER_A" NUMBER, 
	"TEAM_NUMMER_BEHEERDER_A" VARCHAR2(6 CHAR), 
	"BEDRIJF_NAAM" VARCHAR2(80 CHAR), 
	"BEDRIJF_ADRES" VARCHAR2(100 CHAR), 
	"BEDRIJF_POSTCODE" VARCHAR2(6 CHAR), 
	"BEDRIJF_PLAATS" VARCHAR2(80 CHAR), 
	"KVK_NUMMER" VARCHAR2(20 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table DBVI_F_DETAILS_UITGEVOERD
--------------------------------------------------------

  CREATE TABLE "VWASAS"."DBVI_F_DETAILS_UITGEVOERD" 
   (	"INSPECTIE_ID" VARCHAR2(23 CHAR), 
	"VTT_ID" NUMBER(13,0), 
	"BAT_ID" NUMBER(13,0), 
	"OJT_ID" NUMBER(17,0), 
	"KENMERK_CODE" VARCHAR2(10 CHAR), 
	"AFWIJKING" NUMBER, 
	"MAATREGEL_CORR" NUMBER, 
	"MAATREGEL_RVB" NUMBER, 
	"MAATREGEL_OVERIG" NUMBER, 
	"VOLDOET_NIET" NUMBER, 
	"INTERVENTIE" NUMBER, 
	"AFW_TYPE_V_INCL_INTERVENTIE" NUMBER, 
	"AFW_TYPE_V_EXCL_INTERVENTIE" NUMBER, 
	"AANTAL_BEVINDINGEN" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table DBVI_F_INSPECTIES_AFGEBROKEN
--------------------------------------------------------

  CREATE TABLE "VWASAS"."DBVI_F_INSPECTIES_AFGEBROKEN" 
   (	"INSPECTIE_ID" VARCHAR2(23 CHAR), 
	"VTT_ID" NUMBER(13,0), 
	"VMA_ID" NUMBER(15,0), 
	"INSPECTIE_DATUM_UITGEVOERD" DATE, 
	"SAP_NUMMER_INSPECTEUR" NUMBER(11,0), 
	"INSPECTIE_AID_NUMMER" NUMBER(14,0), 
	"INSPECTIE_SOORT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table DBVI_D_BEDRIJVEN_HIST
--------------------------------------------------------

  CREATE TABLE "VWASAS"."DBVI_D_BEDRIJVEN_HIST" 
   (	"BEGINDATUM" DATE, 
	"EINDDATUM" DATE, 
	"AID_NUMMER_PRIMAIR" NUMBER, 
	"SAP_NUMMER_BEHEERDER_H" NUMBER, 
	"HOOFDACTIVITEIT" VARCHAR2(1 CHAR), 
	"TOEZICHTSPROFIEL" VARCHAR2(2 CHAR), 
	"DOMEIN" VARCHAR2(1 CHAR), 
	"KOPPELS_PER_SLACHTSHIFT" VARCHAR2(3 CHAR), 
	"FREQ_VMA_VANGLETSEL" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table DBVI_D_ERKENNINGEN_ACTUEEL
--------------------------------------------------------

  CREATE TABLE "VWASAS"."DBVI_D_ERKENNINGEN_ACTUEEL" 
   (	"AID_NUMMER_PRIMAIR" NUMBER, 
	"ERKENNING_CATEGORIE" VARCHAR2(15 CHAR), 
	"ERKENNING_SUBCATEGORIE" VARCHAR2(40 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table DBVI_D_INSPECTIESOORT
--------------------------------------------------------

  CREATE TABLE "VWASAS"."DBVI_D_INSPECTIESOORT" 
   (	"INSPECTIE_SOORT" NUMBER, 
	"INSPECTIE_SOORT_NAAM" VARCHAR2(20 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table DBVI_D_SUBBEDRIJVEN_ACTUEEL
--------------------------------------------------------

  CREATE TABLE "VWASAS"."DBVI_D_SUBBEDRIJVEN_ACTUEEL" 
   (	"AID_NUMMER_PRIMAIR" NUMBER, 
	"AID_NUMMER" NUMBER, 
	"BEDRIJF_NAAM" VARCHAR2(80 CHAR), 
	"BEDRIJF_ADRES" VARCHAR2(100 CHAR), 
	"BEDRIJF_POSTCODE" VARCHAR2(6 CHAR), 
	"BEDRIJF_PLAATS" VARCHAR2(80 CHAR), 
	"KVK_NUMMER" VARCHAR2(20 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table DBVI_D_ORGANISATIE
--------------------------------------------------------

  CREATE TABLE "VWASAS"."DBVI_D_ORGANISATIE" 
   (	"BEGINDATUM" DATE, 
	"EINDDATUM" DATE, 
	"SAP_NUMMER" NUMBER, 
	"NAAM_MEDEWERKER" VARCHAR2(50 CHAR), 
	"KPN_TEAM" VARCHAR2(6 CHAR), 
	"TEAM_NAAM" VARCHAR2(40 CHAR), 
	"KPN_AFDELING" VARCHAR2(6 CHAR), 
	"AFDELING" VARCHAR2(50 CHAR), 
	"KPN_DIVISIE" VARCHAR2(6 CHAR), 
	"DIVISIE" VARCHAR2(50 CHAR), 
	"KPN_DIRECTIE" VARCHAR2(6 CHAR), 
	"DIRECTIE" VARCHAR2(50 CHAR), 
	"KPN_ORGANISATIE" VARCHAR2(6 CHAR), 
	"ORGANISATIE" VARCHAR2(50 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table DBVI_D_PROGRAMMA_ERKENNINGEN
--------------------------------------------------------

  CREATE TABLE "VWASAS"."DBVI_D_PROGRAMMA_ERKENNINGEN" 
   (	"VMA_ID" NUMBER, 
	"PROGRAMMA_NAAM" VARCHAR2(240 CHAR), 
	"ERKENNING_CATEGORIE" VARCHAR2(15 CHAR), 
	"ERKENNING_SUBCATEGORIE" VARCHAR2(40 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table DBVI_F_INSPECTIES_GEPLAND
--------------------------------------------------------

  CREATE TABLE "VWASAS"."DBVI_F_INSPECTIES_GEPLAND" 
   (	"INSPECTIE_ID" VARCHAR2(23 CHAR), 
	"INSPECTIE_DATUM_GEPLAND" DATE, 
	"AID_NUMMER_PRIMAIR" NUMBER, 
	"VMA_ID" NUMBER(15,0), 
	"SAP_NUMMER_LKE" NUMBER, 
	"INSPECTIE_SOORT" NUMBER, 
	"KOELVRIESHUIS" NUMBER, 
	"PLUIMVEE" NUMBER, 
	"ROODVLEES" NUMBER, 
	"UITSNIJDERIJ" NUMBER, 
	"WILD" NUMBER, 
	"LEVENDVEE" NUMBER, 
	"LV_DP" NUMBER, 
	"LV_LP" NUMBER, 
	"LV_PP" NUMBER, 
	"LV_PS" NUMBER, 
	"LV_QB" NUMBER, 
	"LV_RO" NUMBER, 
	"LV_VC" NUMBER, 
	"AANTAL_INSPECTIES" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table DBVI_D_DETAILS_UITGEVOERD
--------------------------------------------------------

  CREATE TABLE "VWASAS"."DBVI_D_DETAILS_UITGEVOERD" 
   (	"INSPECTIE_ID" VARCHAR2(23 CHAR), 
	"VTT_ID" NUMBER(13,0), 
	"BAT_ID" NUMBER(13,0), 
	"OJT_ID" NUMBER(17,0), 
	"KENMERK_CODE" VARCHAR2(10 CHAR), 
	"SPT_ID" NUMBER(13,0), 
	"SPT_VRAAG" VARCHAR2(210 CHAR), 
	"SPT_VOLGORDE" NUMBER, 
	"GEGEVENSTYPE" VARCHAR2(1 CHAR), 
	"ANTWOORD_A" VARCHAR2(200 CHAR), 
	"ANTWOORD_N" NUMBER(19,2), 
	"ANTWOORD_D" DATE, 
	"ANTWOORD_V" VARCHAR2(500 CHAR), 
	"BEVINDING" VARCHAR2(500 CHAR), 
	"BETROKKENE_1_RELATIENUMMER" NUMBER(14,0), 
	"BETROKKENE_1" VARCHAR2(100 CHAR), 
	"BETROKKENE_2_RELATIENUMMER" NUMBER(14,0), 
	"BETROKKENE_2" VARCHAR2(100 CHAR), 
	"BETROKKENE_3_RELATIENUMMER" NUMBER(14,0), 
	"BETROKKENE_3" VARCHAR2(100 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table DBVI_F_DETAILS_AFGEBROKEN
--------------------------------------------------------

  CREATE TABLE "VWASAS"."DBVI_F_DETAILS_AFGEBROKEN" 
   (	"INSPECTIE_ID" VARCHAR2(23 CHAR), 
	"VTT_ID" NUMBER(13,0), 
	"BAT_ID" NUMBER(13,0), 
	"OJT_ID" NUMBER(17,0), 
	"KENMERK_CODE" VARCHAR2(10 CHAR), 
	"AFWIJKING" NUMBER, 
	"MAATREGEL_CORR" NUMBER, 
	"MAATREGEL_RVB" NUMBER, 
	"MAATREGEL_OVERIG" NUMBER, 
	"VOLDOET_NIET" NUMBER, 
	"INTERVENTIE" NUMBER, 
	"AFW_TYPE_V_INCL_INTERVENTIE" NUMBER, 
	"AFW_TYPE_V_EXCL_INTERVENTIE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table DBVI_D_TEAM_ORG_ACTUEEL
--------------------------------------------------------

  CREATE TABLE "VWASAS"."DBVI_D_TEAM_ORG_ACTUEEL" 
   (	"KPN_TEAM" VARCHAR2(6 CHAR), 
	"TEAM_NAAM" VARCHAR2(40 CHAR), 
	"KPN_AFDELING" VARCHAR2(6 CHAR), 
	"AFDELING" VARCHAR2(50 CHAR), 
	"KPN_DIVISIE" VARCHAR2(6 CHAR), 
	"DIVISIE" VARCHAR2(50 CHAR), 
	"KPN_DIRECTIE" VARCHAR2(6 CHAR), 
	"DIRECTIE" VARCHAR2(50 CHAR), 
	"KPN_ORGANISATIE" VARCHAR2(6 CHAR), 
	"ORGANISATIE" VARCHAR2(50 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table DBVI_D_ERKENNINGEN
--------------------------------------------------------

  CREATE TABLE "VWASAS"."DBVI_D_ERKENNINGEN" 
   (	"AID_NUMMER_PRIMAIR" NUMBER, 
	"ERKENNING_CATEGORIE" VARCHAR2(15 CHAR), 
	"ERKENNING_SUBCATEGORIE" VARCHAR2(40 CHAR), 
	"BEGINDATUM" DATE, 
	"EINDDATUM" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table DBVI_D_INSPECTIES_UITGEVOERD
--------------------------------------------------------

  CREATE TABLE "VWASAS"."DBVI_D_INSPECTIES_UITGEVOERD" 
   (	"INSPECTIE_ID" VARCHAR2(23 CHAR), 
	"VTT_ID" NUMBER(13,0), 
	"VDT_ID" NUMBER(15,0), 
	"INSPECTIE_BEDRIJFSNAAM" VARCHAR2(90 CHAR), 
	"INSPECTIE_ADRES" VARCHAR2(255 CHAR), 
	"INSPECTIE_POSTCODE" VARCHAR2(6 CHAR), 
	"INSPECTIE_PLAATSNAAM" VARCHAR2(255 CHAR), 
	"HERINSPECTIE_AANGEZEGD" NUMBER, 
	"OPSPORINGSKOPPELING" VARCHAR2(1 CHAR), 
	"INSPECTIE_SOORT_NAAM" VARCHAR2(20 CHAR), 
	"D_KOELVRIESHUIS" NUMBER, 
	"D_PLUIMVEE" NUMBER, 
	"D_ROODVLEES" NUMBER, 
	"D_UITSNIJDERIJ" NUMBER, 
	"D_WILD" NUMBER, 
	"D_LEVENDVEE" NUMBER, 
	"D_LV_DP" NUMBER, 
	"D_LV_LP" NUMBER, 
	"D_LV_PP" NUMBER, 
	"D_LV_PS" NUMBER, 
	"D_LV_QB" NUMBER, 
	"D_LV_RO" NUMBER, 
	"D_LV_VC" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table DBVI_D_INSPECTIES_GEPLAND
--------------------------------------------------------

  CREATE TABLE "VWASAS"."DBVI_D_INSPECTIES_GEPLAND" 
   (	"INSPECTIE_ID" VARCHAR2(23 CHAR), 
	"INSPECTIE_STATUS" VARCHAR2(1 CHAR), 
	"INSPECTIE_BEDRIJFSNAAM" VARCHAR2(90 CHAR), 
	"INSPECTIE_ADRES" VARCHAR2(255 CHAR), 
	"INSPECTIE_POSTCODE" VARCHAR2(6 CHAR), 
	"INSPECTIE_PLAATSNAAM" VARCHAR2(255 CHAR), 
	"INSPECTIE_SOORT_NAAM" VARCHAR2(20 CHAR), 
	"D_KOELVRIESHUIS" NUMBER, 
	"D_PLUIMVEE" NUMBER, 
	"D_ROODVLEES" NUMBER, 
	"D_UITSNIJDERIJ" NUMBER, 
	"D_WILD" NUMBER, 
	"D_LEVENDVEE" NUMBER, 
	"D_LV_DP" NUMBER, 
	"D_LV_LP" NUMBER, 
	"D_LV_PP" NUMBER, 
	"D_LV_PS" NUMBER, 
	"D_LV_QB" NUMBER, 
	"D_LV_RO" NUMBER, 
	"D_LV_VC" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table DBVI_D_INSPECTIES_AFGEBROKEN
--------------------------------------------------------

  CREATE TABLE "VWASAS"."DBVI_D_INSPECTIES_AFGEBROKEN" 
   (	"INSPECTIE_ID" VARCHAR2(23 CHAR), 
	"VTT_ID" NUMBER(13,0), 
	"VDT_ID" NUMBER(15,0), 
	"INSPECTIE_DATUM_AFGEBROKEN" DATE, 
	"INSPECTIE_STATUS" VARCHAR2(1 CHAR), 
	"INSPECTIE_BEDRIJFSNAAM" VARCHAR2(90 CHAR), 
	"INSPECTIE_ADRES" VARCHAR2(255 CHAR), 
	"INSPECTIE_POSTCODE" VARCHAR2(6 CHAR), 
	"INSPECTIE_PLAATSNAAM" VARCHAR2(255 CHAR), 
	"OPSPORINGSKOPPELING" VARCHAR2(1 CHAR), 
	"HERINSPECTIE_AANGEZEGD" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table DBVI_D_PROGRAMMA
--------------------------------------------------------

  CREATE TABLE "VWASAS"."DBVI_D_PROGRAMMA" 
   (	"VMA_ID" NUMBER, 
	"PROGRAMMA_NAAM" VARCHAR2(240 CHAR), 
	"GEPLAND" VARCHAR2(1 CHAR), 
	"WERKPAKKET" VARCHAR2(40 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table DBVI_D_DETAILS_AFGEBROKEN
--------------------------------------------------------

  CREATE TABLE "VWASAS"."DBVI_D_DETAILS_AFGEBROKEN" 
   (	"INSPECTIE_ID" VARCHAR2(23 CHAR), 
	"VTT_ID" NUMBER(13,0), 
	"BAT_ID" NUMBER(13,0), 
	"OJT_ID" NUMBER(17,0), 
	"KENMERK_CODE" VARCHAR2(10 CHAR), 
	"SPT_ID" NUMBER(13,0), 
	"SPT_VRAAG" VARCHAR2(210 CHAR), 
	"SPT_VOLGORDE" NUMBER, 
	"GEGEVENSTYPE" VARCHAR2(1 CHAR), 
	"ANTWOORD_A" VARCHAR2(200 CHAR), 
	"ANTWOORD_N" NUMBER(19,2), 
	"ANTWOORD_D" DATE, 
	"ANTWOORD_V" VARCHAR2(500 CHAR), 
	"BETROKKENE_1" VARCHAR2(100 CHAR), 
	"BETROKKENE_2" VARCHAR2(100 CHAR), 
	"BETROKKENE_3" VARCHAR2(100 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table DBVI_F_BETROKKENEN_UITGEVOERD
--------------------------------------------------------

  CREATE TABLE "VWASAS"."DBVI_F_BETROKKENEN_UITGEVOERD" 
   (	"INSPECTIE_ID" VARCHAR2(23 CHAR), 
	"VTT_ID" NUMBER(13,0), 
	"BETROKKENE_RELATIENUMMER" NUMBER(14,0), 
	"AANTAL_BETROKKENEN" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table DBVI_D_BEREKENINGSDATUM
--------------------------------------------------------

  CREATE TABLE "VWASAS"."DBVI_D_BEREKENINGSDATUM" 
   (	"BEREKENINGSDATUM" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table DBVI_D_ORGANISATIE_ACTUEEL
--------------------------------------------------------

  CREATE TABLE "VWASAS"."DBVI_D_ORGANISATIE_ACTUEEL" 
   (	"SAP_NUMMER" NUMBER, 
	"NAAM_MEDEWERKER" VARCHAR2(50 CHAR), 
	"KPN_TEAM" VARCHAR2(6 CHAR), 
	"TEAM_NAAM" VARCHAR2(40 CHAR), 
	"KPN_AFDELING" VARCHAR2(6 CHAR), 
	"AFDELING" VARCHAR2(50 CHAR), 
	"KPN_DIVISIE" VARCHAR2(6 CHAR), 
	"DIVISIE" VARCHAR2(50 CHAR), 
	"KPN_DIRECTIE" VARCHAR2(6 CHAR), 
	"DIRECTIE" VARCHAR2(50 CHAR), 
	"KPN_ORGANISATIE" VARCHAR2(6 CHAR), 
	"ORGANISATIE" VARCHAR2(50 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table DBVI_F_INSPECTIES_UITGEVOERD
--------------------------------------------------------

  CREATE TABLE "VWASAS"."DBVI_F_INSPECTIES_UITGEVOERD" 
   (	"INSPECTIE_ID" VARCHAR2(23 CHAR), 
	"VTT_ID" NUMBER(13,0), 
	"INSPECTIE_DATUM_UITGEVOERD" DATE, 
	"VMA_ID" NUMBER(15,0), 
	"AID_NUMMER_PRIMAIR" NUMBER, 
	"INSPECTIE_AID_NUMMER" NUMBER(14,0), 
	"SAP_NUMMER_INSPECTEUR" NUMBER(11,0), 
	"INSPECTIE_SOORT" NUMBER, 
	"AANTAL_AFWIJKINGEN" NUMBER, 
	"AANTAL_MAATREGELEN_CORR" NUMBER, 
	"AANTAL_MAATREGELEN_RVB" NUMBER, 
	"AANTAL_MAATREGELEN_OVERIG" NUMBER, 
	"AANTAL_VOLDOET_NIET" NUMBER, 
	"AANTAL_INTERVENTIES" NUMBER, 
	"AANTAL_AFW_V_INCL_INTERVENTIES" NUMBER, 
	"AANTAL_AFW_V_EXCL_INTERVENTIES" NUMBER, 
	"KOELVRIESHUIS" NUMBER, 
	"PLUIMVEE" NUMBER, 
	"ROODVLEES" NUMBER, 
	"UITSNIJDERIJ" NUMBER, 
	"WILD" NUMBER, 
	"LEVENDVEE" NUMBER, 
	"LV_DP" NUMBER, 
	"LV_LP" NUMBER, 
	"LV_PP" NUMBER, 
	"LV_PS" NUMBER, 
	"LV_QB" NUMBER, 
	"LV_RO" NUMBER, 
	"LV_VC" NUMBER, 
	"SAP_NUMMER_LKE" NUMBER, 
	"IS_BASIS" NUMBER, 
	"IS_HER" NUMBER, 
	"AANTAL_INSPECTIES" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table DBVI_D_BETROKKENEN_UITGEVOERD
--------------------------------------------------------

  CREATE TABLE "VWASAS"."DBVI_D_BETROKKENEN_UITGEVOERD" 
   (	"BETROKKENE_RELATIENUMMER" NUMBER(14,0), 
	"BETROKKENE_NAAM" VARCHAR2(80 CHAR), 
	"BETROKKENE_ADRES" VARCHAR2(255 CHAR), 
	"BETROKKENE_POSTCODE" VARCHAR2(6 CHAR), 
	"BETROKKENE_PLAATSNAAM" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
--------------------------------------------------------
--  Constraints for Table DBVI_D_BETROKKENEN_UITGEVOERD
--------------------------------------------------------

  ALTER TABLE "VWASAS"."DBVI_D_BETROKKENEN_UITGEVOERD" MODIFY ("BETROKKENE_NAAM" NOT NULL ENABLE);
  ALTER TABLE "VWASAS"."DBVI_D_BETROKKENEN_UITGEVOERD" MODIFY ("BETROKKENE_ADRES" NOT NULL ENABLE);
  ALTER TABLE "VWASAS"."DBVI_D_BETROKKENEN_UITGEVOERD" MODIFY ("BETROKKENE_POSTCODE" NOT NULL ENABLE);
  ALTER TABLE "VWASAS"."DBVI_D_BETROKKENEN_UITGEVOERD" MODIFY ("BETROKKENE_PLAATSNAAM" NOT NULL ENABLE);
