--------------------------------------------------------
--  DDL for Table VGC_BESLISSING
--------------------------------------------------------

  CREATE TABLE "VWASAS"."VGC_BESLISSING" 
   (	"BESLISSING_ID" NUMBER(10,0), 
	"ARTIKEL_8_IND" VARCHAR2(1 CHAR), 
	"WETTELIJKE_BASIS" VARCHAR2(5 CHAR), 
	"WETTELIJKE_BASIS_NAAM" VARCHAR2(240 CHAR), 
	"DEFINITIEF_IND" VARCHAR2(1 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
  GRANT DELETE ON "VWASAS"."VGC_BESLISSING" TO "METEOOR_WORK";
  GRANT INSERT ON "VWASAS"."VGC_BESLISSING" TO "METEOOR_WORK";
  GRANT SELECT ON "VWASAS"."VGC_BESLISSING" TO "METEOOR_WORK";
  GRANT UPDATE ON "VWASAS"."VGC_BESLISSING" TO "METEOOR_WORK";
--------------------------------------------------------
--  DDL for Table VGC_MDB_D_AANVRAGER
--------------------------------------------------------

  CREATE TABLE "VWASAS"."VGC_MDB_D_AANVRAGER" 
   (	"ID" NUMBER(12,0), 
	"LND_ID" NUMBER(12,0), 
	"RLE_TYPE" VARCHAR2(5 CHAR), 
	"NAAM" VARCHAR2(70 CHAR), 
	"ADRES" VARCHAR2(58 CHAR), 
	"HUISNUMMER" VARCHAR2(10 CHAR), 
	"POSTCODE" VARCHAR2(9 CHAR), 
	"PLAATS" VARCHAR2(35 CHAR), 
	"TELEFOONNUMMER" VARCHAR2(35 CHAR), 
	"FAXNUMMER" VARCHAR2(35 CHAR), 
	"AANGEVERNUMMER" VARCHAR2(15 CHAR), 
	"LAND" VARCHAR2(70 CHAR), 
	"LAND_CODE" VARCHAR2(3 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table VGC_PRODUCT
--------------------------------------------------------

  CREATE TABLE "VWASAS"."VGC_PRODUCT" 
   (	"PRODUCT_ID" NUMBER(10,0), 
	"PRODUCT_CODE" VARCHAR2(14 CHAR), 
	"PRODUCT_AARD" VARCHAR2(100 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
  GRANT DELETE ON "VWASAS"."VGC_PRODUCT" TO "METEOOR_WORK";
  GRANT INSERT ON "VWASAS"."VGC_PRODUCT" TO "METEOOR_WORK";
  GRANT SELECT ON "VWASAS"."VGC_PRODUCT" TO "METEOOR_WORK";
  GRANT UPDATE ON "VWASAS"."VGC_PRODUCT" TO "METEOOR_WORK";
--------------------------------------------------------
--  DDL for Table VGC_MDB_F_OVOD
--------------------------------------------------------

  CREATE TABLE "VWASAS"."VGC_MDB_F_OVOD" 
   (	"ID_OMISSIE" NUMBER, 
	"ID_LAND_VAN_OORSPRONG" NUMBER, 
	"ID_PRODUCT_OO" NUMBER, 
	"ID_OMISSIE_IN" NUMBER, 
	"ID_CATEGORIE" NUMBER, 
	"USERID_DOUANE" VARCHAR2(255 CHAR), 
	"ID_MAATREGEL" NUMBER, 
	"GN_CODE_PTJ" VARCHAR2(13 CHAR), 
	"ID_VETERIN_BESTEMMING" NUMBER(10,0), 
	"ID_AANVRAGER" NUMBER(10,0), 
	"DATUM_OMISSIE" DATE, 
	"GDBNUMMER" NUMBER, 
	"OMSCHRIJVINGOMISSIE" VARCHAR2(255 CHAR), 
	"ONDERNOMENAKTIE" VARCHAR2(50 CHAR), 
	"INVOERDATUM" DATE, 
	"INGEVOERDDOOR" VARCHAR2(50 CHAR), 
	"AANGEPASTDATUM" DATE, 
	"AANGEPASTDOOR" VARCHAR2(50 CHAR), 
	"OMISSIEWAARGENOMENDOOR" VARCHAR2(50 CHAR), 
	"GGS_NUMMER" VARCHAR2(10 CHAR), 
	"DATUM_AANKOMST" DATE, 
	"DATUM_ONDERTEKENING" DATE, 
	"PTJ_TYPE" VARCHAR2(5 CHAR), 
	"BIP" VARCHAR2(70 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table VGC_XCSE
--------------------------------------------------------

  CREATE TABLE "VWASAS"."VGC_XCSE" 
   (	"ID" NUMBER(10,0), 
	"CODE" VARCHAR2(10 CHAR), 
	"OMSCHRIJVING" VARCHAR2(200 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
  GRANT DELETE ON "VWASAS"."VGC_XCSE" TO "METEOOR_WORK";
  GRANT INSERT ON "VWASAS"."VGC_XCSE" TO "METEOOR_WORK";
  GRANT SELECT ON "VWASAS"."VGC_XCSE" TO "METEOOR_WORK";
  GRANT UPDATE ON "VWASAS"."VGC_XCSE" TO "METEOOR_WORK";
--------------------------------------------------------
--  DDL for Table VGC_XIMPORTEUR
--------------------------------------------------------

  CREATE TABLE "VWASAS"."VGC_XIMPORTEUR" 
   (	"GGS_NUMMER" VARCHAR2(10 CHAR), 
	"NAAM_IMPORTEUR" VARCHAR2(70 CHAR), 
	"ADRES_IMPORTEUR" VARCHAR2(200 CHAR), 
	"POSTCODE_IMPORTEUR" VARCHAR2(9 CHAR), 
	"LAND_IMPORTEUR" VARCHAR2(3 CHAR), 
	"IM_TRACES_ID" VARCHAR2(35 CHAR), 
	"IM_HUISNUMMER" VARCHAR2(5 CHAR), 
	"IM_HUISNUMMERTOEVOEGING" VARCHAR2(12 CHAR), 
	"IM_PLAATS" VARCHAR2(30 CHAR), 
	"IM_POSTCODE" VARCHAR2(9 CHAR), 
	"IM_STRAAT_POSTBUS" VARCHAR2(100 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
  GRANT DELETE ON "VWASAS"."VGC_XIMPORTEUR" TO "METEOOR_WORK";
  GRANT INSERT ON "VWASAS"."VGC_XIMPORTEUR" TO "METEOOR_WORK";
  GRANT SELECT ON "VWASAS"."VGC_XIMPORTEUR" TO "METEOOR_WORK";
  GRANT UPDATE ON "VWASAS"."VGC_XIMPORTEUR" TO "METEOOR_WORK";
--------------------------------------------------------
--  DDL for Table VGC_MDB_D_DOUANE_OA
--------------------------------------------------------

  CREATE TABLE "VWASAS"."VGC_MDB_D_DOUANE_OA" 
   (	"USERNAME_DOUANE" VARCHAR2(255 CHAR), 
	"ID" NUMBER, 
	"NAAM" VARCHAR2(255 CHAR), 
	"USERNAME" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table VGC_BESLISSING_TYPE
--------------------------------------------------------

  CREATE TABLE "VWASAS"."VGC_BESLISSING_TYPE" 
   (	"BESLISSINGTYPE_ID" NUMBER(10,0), 
	"BESLISSINGTYPE_CODE" VARCHAR2(10 CHAR), 
	"BESLISSINGTYPE_NAAM" VARCHAR2(70 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
  GRANT DELETE ON "VWASAS"."VGC_BESLISSING_TYPE" TO "METEOOR_WORK";
  GRANT INSERT ON "VWASAS"."VGC_BESLISSING_TYPE" TO "METEOOR_WORK";
  GRANT SELECT ON "VWASAS"."VGC_BESLISSING_TYPE" TO "METEOOR_WORK";
  GRANT UPDATE ON "VWASAS"."VGC_BESLISSING_TYPE" TO "METEOOR_WORK";
--------------------------------------------------------
--  DDL for Table VGC_MDB_D_VETERIN_BESTEMMING
--------------------------------------------------------

  CREATE TABLE "VWASAS"."VGC_MDB_D_VETERIN_BESTEMMING" 
   (	"ID" NUMBER(12,0), 
	"CODE" VARCHAR2(10 CHAR), 
	"NAAM" VARCHAR2(70 CHAR), 
	"OMSCHRIJVING" VARCHAR2(200 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table VGC_XTRANSPORTEUR
--------------------------------------------------------

  CREATE TABLE "VWASAS"."VGC_XTRANSPORTEUR" 
   (	"GGS_NUMMER" VARCHAR2(10 CHAR), 
	"TRANSPORTEURNAAM" VARCHAR2(70 CHAR), 
	"TRANSPORTEURADRES" VARCHAR2(200 CHAR), 
	"TRANSPORTEURPOSTCODE" VARCHAR2(9 CHAR), 
	"TRANSPORTEURLAND" VARCHAR2(3 CHAR), 
	"TR_TRACES_ID" VARCHAR2(35 CHAR), 
	"TR_HUISNUMMER" VARCHAR2(5 CHAR), 
	"TR_HUISNUMMERTOEVOEGING" VARCHAR2(12 CHAR), 
	"TR_PLAATS" VARCHAR2(30 CHAR), 
	"TR_POSTCODE" VARCHAR2(9 CHAR), 
	"TR_STRAAT_POSTBUS" VARCHAR2(100 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
  GRANT DELETE ON "VWASAS"."VGC_XTRANSPORTEUR" TO "METEOOR_WORK";
  GRANT INSERT ON "VWASAS"."VGC_XTRANSPORTEUR" TO "METEOOR_WORK";
  GRANT SELECT ON "VWASAS"."VGC_XTRANSPORTEUR" TO "METEOOR_WORK";
  GRANT UPDATE ON "VWASAS"."VGC_XTRANSPORTEUR" TO "METEOOR_WORK";
--------------------------------------------------------
--  DDL for Table VGC_FEITEN
--------------------------------------------------------

  CREATE TABLE "VWASAS"."VGC_FEITEN" 
   (	"COLLI_ID" NUMBER(10,0), 
	"PTJ_ID" NUMBER(10,0), 
	"RELATIE_ID" NUMBER(10,0), 
	"KPT_ID_AANGEB_SIP" NUMBER(10,0), 
	"KPT_ID_AANGEB_BIP" NUMBER(10,0), 
	"BESTEMMING_ID" NUMBER(10,0), 
	"BESLISSING_ID" NUMBER(10,0), 
	"GEBRUIKSDOEL_ID" NUMBER(10,0), 
	"BESLISSINGTYPE_ID" NUMBER(10,0), 
	"PRODUCT_ID" NUMBER(10,0), 
	"CREATION_DATE" DATE, 
	"GEWICHT_NETTO" NUMBER, 
	"GEWICHT_BRUTO" NUMBER, 
	"PROD_AANTAL" NUMBER, 
	"AANTAL" NUMBER, 
	"VOORNEMEN_TOT_WEIGEREN" NUMBER, 
	"MONSTERNAME" NUMBER, 
	"POSITIEF_MONSTERNAME" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
  GRANT DELETE ON "VWASAS"."VGC_FEITEN" TO "METEOOR_WORK";
  GRANT INSERT ON "VWASAS"."VGC_FEITEN" TO "METEOOR_WORK";
  GRANT SELECT ON "VWASAS"."VGC_FEITEN" TO "METEOOR_WORK";
  GRANT UPDATE ON "VWASAS"."VGC_FEITEN" TO "METEOOR_WORK";
--------------------------------------------------------
--  DDL for Table VGC_XPARTIJINFO
--------------------------------------------------------

  CREATE TABLE "VWASAS"."VGC_XPARTIJINFO" 
   (	"GGS_NUMMER" VARCHAR2(10 CHAR), 
	"NAAM_VAARTUIG" VARCHAR2(70 CHAR), 
	"EU_WAARDIG_IND" VARCHAR2(1 CHAR), 
	"NAAM_HAVEN" VARCHAR2(70 CHAR), 
	"OPSLAG" VARCHAR2(5 CHAR), 
	"OORSPRONG" VARCHAR2(100 CHAR), 
	"ERKENNINGSNUMMER" VARCHAR2(70 CHAR), 
	"REGISTRATIENUMMER" VARCHAR2(35 CHAR), 
	"VAARTUIG_VLUCHTNUMMER" VARCHAR2(25 CHAR), 
	"VRACHTBRIEFNUMMER" VARCHAR2(35 CHAR), 
	"NAAM_ONDERTEKENAAR" VARCHAR2(70 CHAR), 
	"PLAATS_ONDERTEKENING" VARCHAR2(70 CHAR), 
	"WERKLIJSTROL" VARCHAR2(5 CHAR), 
	"AANGIFTEJAAR" NUMBER(3,0), 
	"AANGIFTEVOLGNUMMER" NUMBER(9,0), 
	"AANTAL_DIEREN" NUMBER(11,0), 
	"TRACES_COMPLEMENT_ID" VARCHAR2(35 CHAR), 
	"TRACES_SPECIES_ID" VARCHAR2(35 CHAR), 
	"TRACES_CERTIFICAAT_ID" VARCHAR2(30 CHAR), 
	"BEWAKINGTMN_OVN_IND" VARCHAR2(1 CHAR), 
	"AF_HUISNUMMER" VARCHAR2(5 CHAR), 
	"AF_HUISNUMMERTOEVOEGING" VARCHAR2(12 CHAR), 
	"AF_PLAATS" VARCHAR2(30 CHAR), 
	"AF_POSTCODE" VARCHAR2(9 CHAR), 
	"SOORT_IMPORT" VARCHAR2(5 CHAR), 
	"AF_STRAAT_POSTBUS" VARCHAR2(100 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
  GRANT DELETE ON "VWASAS"."VGC_XPARTIJINFO" TO "METEOOR_WORK";
  GRANT INSERT ON "VWASAS"."VGC_XPARTIJINFO" TO "METEOOR_WORK";
  GRANT SELECT ON "VWASAS"."VGC_XPARTIJINFO" TO "METEOOR_WORK";
  GRANT UPDATE ON "VWASAS"."VGC_XPARTIJINFO" TO "METEOOR_WORK";
--------------------------------------------------------
--  DDL for Table VGC_XPTJTYPE
--------------------------------------------------------

  CREATE TABLE "VWASAS"."VGC_XPTJTYPE" 
   (	"PTJ_TYPE" VARCHAR2(3 CHAR), 
	"PTJ_OMSCHR" VARCHAR2(30 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
  GRANT DELETE ON "VWASAS"."VGC_XPTJTYPE" TO "METEOOR_WORK";
  GRANT INSERT ON "VWASAS"."VGC_XPTJTYPE" TO "METEOOR_WORK";
  GRANT SELECT ON "VWASAS"."VGC_XPTJTYPE" TO "METEOOR_WORK";
  GRANT UPDATE ON "VWASAS"."VGC_XPTJTYPE" TO "METEOOR_WORK";
--------------------------------------------------------
--  DDL for Table VGC_KEURPUNT
--------------------------------------------------------

  CREATE TABLE "VWASAS"."VGC_KEURPUNT" 
   (	"KPT_ID_AANGEB_SIP" NUMBER(10,0), 
	"KEURPUNT_NAAM" VARCHAR2(70 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
  GRANT DELETE ON "VWASAS"."VGC_KEURPUNT" TO "METEOOR_WORK";
  GRANT INSERT ON "VWASAS"."VGC_KEURPUNT" TO "METEOOR_WORK";
  GRANT SELECT ON "VWASAS"."VGC_KEURPUNT" TO "METEOOR_WORK";
  GRANT UPDATE ON "VWASAS"."VGC_KEURPUNT" TO "METEOOR_WORK";
--------------------------------------------------------
--  DDL for Table VGC_MDB_D_OMISSIE_IN
--------------------------------------------------------

  CREATE TABLE "VWASAS"."VGC_MDB_D_OMISSIE_IN" 
   (	"ID" NUMBER, 
	"OMISSIE_VASTGESTELD_IN" VARCHAR2(50 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table VGC_XSTSTATUS
--------------------------------------------------------

  CREATE TABLE "VWASAS"."VGC_XSTSTATUS" 
   (	"ST_STATUS" VARCHAR2(3 CHAR), 
	"ST_OMSCHR" VARCHAR2(30 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
  GRANT DELETE ON "VWASAS"."VGC_XSTSTATUS" TO "METEOOR_WORK";
  GRANT INSERT ON "VWASAS"."VGC_XSTSTATUS" TO "METEOOR_WORK";
  GRANT SELECT ON "VWASAS"."VGC_XSTSTATUS" TO "METEOOR_WORK";
  GRANT UPDATE ON "VWASAS"."VGC_XSTSTATUS" TO "METEOOR_WORK";
--------------------------------------------------------
--  DDL for Table VGC_XVBG
--------------------------------------------------------

  CREATE TABLE "VWASAS"."VGC_XVBG" 
   (	"ID" NUMBER(10,0), 
	"CODE" VARCHAR2(10 CHAR), 
	"NAAM" VARCHAR2(70 CHAR), 
	"OMSCHRIJVING" VARCHAR2(200 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
  GRANT DELETE ON "VWASAS"."VGC_XVBG" TO "METEOOR_WORK";
  GRANT INSERT ON "VWASAS"."VGC_XVBG" TO "METEOOR_WORK";
  GRANT SELECT ON "VWASAS"."VGC_XVBG" TO "METEOOR_WORK";
  GRANT UPDATE ON "VWASAS"."VGC_XVBG" TO "METEOOR_WORK";
--------------------------------------------------------
--  DDL for Table VGC_XVERZENDER
--------------------------------------------------------

  CREATE TABLE "VWASAS"."VGC_XVERZENDER" 
   (	"GGS_NUMMER" VARCHAR2(10 CHAR), 
	"NAAM_VERZENDER" VARCHAR2(70 CHAR), 
	"ADRES_VERZENDER" VARCHAR2(200 CHAR), 
	"LAND_VERZENDER" VARCHAR2(3 CHAR), 
	"DP_TRACES_ID" VARCHAR2(35 CHAR), 
	"DP_HUISNUMMER" VARCHAR2(5 CHAR), 
	"DP_HUISNUMMERTOEVOEGING" VARCHAR2(12 CHAR), 
	"DP_PLAATS" VARCHAR2(30 CHAR), 
	"DP_POSTCODE" VARCHAR2(9 CHAR), 
	"DP_STRAAT_POSTBUS" VARCHAR2(100 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
  GRANT DELETE ON "VWASAS"."VGC_XVERZENDER" TO "METEOOR_WORK";
  GRANT INSERT ON "VWASAS"."VGC_XVERZENDER" TO "METEOOR_WORK";
  GRANT SELECT ON "VWASAS"."VGC_XVERZENDER" TO "METEOOR_WORK";
  GRANT UPDATE ON "VWASAS"."VGC_XVERZENDER" TO "METEOOR_WORK";
--------------------------------------------------------
--  DDL for Table VGC_MDB_D_PROBLEEM
--------------------------------------------------------

  CREATE TABLE "VWASAS"."VGC_MDB_D_PROBLEEM" 
   (	"ID" NUMBER, 
	"PROBLEEM" VARCHAR2(255 CHAR), 
	"ACTIEF" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table VGC_RELATIE
--------------------------------------------------------

  CREATE TABLE "VWASAS"."VGC_RELATIE" 
   (	"RELATIE_ID" NUMBER(10,0), 
	"RELATIE_NAAM" VARCHAR2(70 CHAR), 
	"AANGEVERNUMMER" VARCHAR2(15 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
  GRANT DELETE ON "VWASAS"."VGC_RELATIE" TO "METEOOR_WORK";
  GRANT INSERT ON "VWASAS"."VGC_RELATIE" TO "METEOOR_WORK";
  GRANT SELECT ON "VWASAS"."VGC_RELATIE" TO "METEOOR_WORK";
  GRANT UPDATE ON "VWASAS"."VGC_RELATIE" TO "METEOOR_WORK";
--------------------------------------------------------
--  DDL for Table VGC_XGEADRESSEERDE
--------------------------------------------------------

  CREATE TABLE "VWASAS"."VGC_XGEADRESSEERDE" 
   (	"GGS_NUMMER" VARCHAR2(10 CHAR), 
	"NAAM_GEADRESSEERDE" VARCHAR2(70 CHAR), 
	"ADRES_GEADRESSEERDE" VARCHAR2(200 CHAR), 
	"POSTCODE_GEADRESSEERDE" VARCHAR2(9 CHAR), 
	"LAND_GEADRESSEERDE" VARCHAR2(3 CHAR), 
	"CN_TRACES_ID" VARCHAR2(35 CHAR), 
	"CN_HUISNUMMER" VARCHAR2(5 CHAR), 
	"CN_HUISNUMMERTOEVOEGING" VARCHAR2(12 CHAR), 
	"CN_PLAATS" VARCHAR2(30 CHAR), 
	"CN_POSTCODE" VARCHAR2(9 CHAR), 
	"CN_STRAAT_POSTBUS" VARCHAR2(100 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
  GRANT DELETE ON "VWASAS"."VGC_XGEADRESSEERDE" TO "METEOOR_WORK";
  GRANT INSERT ON "VWASAS"."VGC_XGEADRESSEERDE" TO "METEOOR_WORK";
  GRANT SELECT ON "VWASAS"."VGC_XGEADRESSEERDE" TO "METEOOR_WORK";
  GRANT UPDATE ON "VWASAS"."VGC_XGEADRESSEERDE" TO "METEOOR_WORK";
--------------------------------------------------------
--  DDL for Table VGC_XVERVOLGTRSP
--------------------------------------------------------

  CREATE TABLE "VWASAS"."VGC_XVERVOLGTRSP" 
   (	"GGS_NUMMER" VARCHAR2(10 CHAR), 
	"VERVOLGTRANSPORT" VARCHAR2(5 CHAR), 
	"VERVOLGTRANSPORTID" VARCHAR2(25 CHAR), 
	"REISSCHEMA" VARCHAR2(1 CHAR), 
	"TRANSPORTIDENTIFICATIE" VARCHAR2(25 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
  GRANT DELETE ON "VWASAS"."VGC_XVERVOLGTRSP" TO "METEOOR_WORK";
  GRANT INSERT ON "VWASAS"."VGC_XVERVOLGTRSP" TO "METEOOR_WORK";
  GRANT SELECT ON "VWASAS"."VGC_XVERVOLGTRSP" TO "METEOOR_WORK";
  GRANT UPDATE ON "VWASAS"."VGC_XVERVOLGTRSP" TO "METEOOR_WORK";
--------------------------------------------------------
--  DDL for Table VGC_MDB_D_PRODUCT_OO
--------------------------------------------------------

  CREATE TABLE "VWASAS"."VGC_MDB_D_PRODUCT_OO" 
   (	"ID" NUMBER, 
	"PRODUCT" VARCHAR2(50 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table VGC_XTRANSHIPMENT
--------------------------------------------------------

  CREATE TABLE "VWASAS"."VGC_XTRANSHIPMENT" 
   (	"GGS_NUMMER" VARCHAR2(10 CHAR), 
	"TRS_TERMINAL_VAN_UITGANG" VARCHAR2(35 CHAR), 
	"TRS_UITGANGSDATUM" DATE, 
	"TRS_ID_VERVOERMIDDEL" VARCHAR2(17 CHAR), 
	"TRS_REISNUMMER" VARCHAR2(17 CHAR), 
	"TRS_VRACHTBRIEFNUMMER" VARCHAR2(17 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
  GRANT DELETE ON "VWASAS"."VGC_XTRANSHIPMENT" TO "METEOOR_WORK";
  GRANT INSERT ON "VWASAS"."VGC_XTRANSHIPMENT" TO "METEOOR_WORK";
  GRANT SELECT ON "VWASAS"."VGC_XTRANSHIPMENT" TO "METEOOR_WORK";
  GRANT UPDATE ON "VWASAS"."VGC_XTRANSHIPMENT" TO "METEOOR_WORK";
--------------------------------------------------------
--  DDL for Table VGC_BIP
--------------------------------------------------------

  CREATE TABLE "VWASAS"."VGC_BIP" 
   (	"KPT_ID_AANGEB_BIP" NUMBER(10,0), 
	"BIP_NAAM" VARCHAR2(70 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
  GRANT DELETE ON "VWASAS"."VGC_BIP" TO "METEOOR_WORK";
  GRANT INSERT ON "VWASAS"."VGC_BIP" TO "METEOOR_WORK";
  GRANT SELECT ON "VWASAS"."VGC_BIP" TO "METEOOR_WORK";
  GRANT UPDATE ON "VWASAS"."VGC_BIP" TO "METEOOR_WORK";
--------------------------------------------------------
--  DDL for Table VGC_XGBL
--------------------------------------------------------

  CREATE TABLE "VWASAS"."VGC_XGBL" 
   (	"ID" NUMBER(10,0), 
	"CODE" VARCHAR2(10 CHAR), 
	"GBL_TYPE" VARCHAR2(5 CHAR), 
	"HUMAAN_IND" VARCHAR2(1 CHAR), 
	"NAAM" VARCHAR2(70 CHAR), 
	"OMSCHRIJVING" VARCHAR2(400 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
  GRANT DELETE ON "VWASAS"."VGC_XGBL" TO "METEOOR_WORK";
  GRANT INSERT ON "VWASAS"."VGC_XGBL" TO "METEOOR_WORK";
  GRANT SELECT ON "VWASAS"."VGC_XGBL" TO "METEOOR_WORK";
  GRANT UPDATE ON "VWASAS"."VGC_XGBL" TO "METEOOR_WORK";
--------------------------------------------------------
--  DDL for Table VGC_XGGS_FEIT
--------------------------------------------------------

  CREATE TABLE "VWASAS"."VGC_XGGS_FEIT" 
   (	"ID" NUMBER(10,0), 
	"GGS_NUMMER" VARCHAR2(10 CHAR), 
	"KPT_ID_AANGEB_SIP" NUMBER(10,0), 
	"RLE_ID" NUMBER(10,0), 
	"KPT_ID_DOORV_OVERL_BIP" NUMBER(10,0), 
	"VBG_ID" NUMBER(10,0), 
	"KPT_ID_AANGEB_BIP" NUMBER(10,0), 
	"CSE_ID" NUMBER(10,0), 
	"GBL_ID_NIET_LEVEND" NUMBER(10,0), 
	"GBL_ID_LEVEND" NUMBER(10,0), 
	"GBL_ID_LEVENSMIDDEL" NUMBER(10,0), 
	"PTJ_TYPE" VARCHAR2(5 CHAR), 
	"STATUS" VARCHAR2(5 CHAR), 
	"GN_CODE" VARCHAR2(18 CHAR), 
	"DOCUMENTAFGIFTE_DATUM" DATE, 
	"DATUM_ONDERTEKENING" DATE, 
	"UITSLAGDATUM" DATE, 
	"DATUM_AANKOMST" DATE, 
	"TE_LAAT" VARCHAR2(1 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
  GRANT DELETE ON "VWASAS"."VGC_XGGS_FEIT" TO "METEOOR_WORK";
  GRANT INSERT ON "VWASAS"."VGC_XGGS_FEIT" TO "METEOOR_WORK";
  GRANT SELECT ON "VWASAS"."VGC_XGGS_FEIT" TO "METEOOR_WORK";
  GRANT UPDATE ON "VWASAS"."VGC_XGGS_FEIT" TO "METEOOR_WORK";
--------------------------------------------------------
--  DDL for Table VGC_GEBRUIKSDOEL
--------------------------------------------------------

  CREATE TABLE "VWASAS"."VGC_GEBRUIKSDOEL" 
   (	"GEBRUIKSDOEL_ID" NUMBER(10,0), 
	"GEBRUIKSDOEL_NAAM" VARCHAR2(70 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
  GRANT DELETE ON "VWASAS"."VGC_GEBRUIKSDOEL" TO "METEOOR_WORK";
  GRANT INSERT ON "VWASAS"."VGC_GEBRUIKSDOEL" TO "METEOOR_WORK";
  GRANT SELECT ON "VWASAS"."VGC_GEBRUIKSDOEL" TO "METEOOR_WORK";
  GRANT UPDATE ON "VWASAS"."VGC_GEBRUIKSDOEL" TO "METEOOR_WORK";
--------------------------------------------------------
--  DDL for Table VGC_XAFLEVERADRES
--------------------------------------------------------

  CREATE TABLE "VWASAS"."VGC_XAFLEVERADRES" 
   (	"GGS_NUMMER" VARCHAR2(10 CHAR), 
	"NAAM_ONTVANGER" VARCHAR2(70 CHAR), 
	"ADRES_ONTVANGER" VARCHAR2(200 CHAR), 
	"POSTCODE_ONTVANGER" VARCHAR2(9 CHAR), 
	"LAND_ONTVANGER" VARCHAR2(3 CHAR), 
	"AF_TRACES_ID" VARCHAR2(35 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
  GRANT DELETE ON "VWASAS"."VGC_XAFLEVERADRES" TO "METEOOR_WORK";
  GRANT INSERT ON "VWASAS"."VGC_XAFLEVERADRES" TO "METEOOR_WORK";
  GRANT SELECT ON "VWASAS"."VGC_XAFLEVERADRES" TO "METEOOR_WORK";
  GRANT UPDATE ON "VWASAS"."VGC_XAFLEVERADRES" TO "METEOOR_WORK";
--------------------------------------------------------
--  DDL for Table VGC_MDB_D_MAATREGEL
--------------------------------------------------------

  CREATE TABLE "VWASAS"."VGC_MDB_D_MAATREGEL" 
   (	"ID" NUMBER, 
	"MAATREGEL" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table VGC_MDB_D_DOUANE_OO
--------------------------------------------------------

  CREATE TABLE "VWASAS"."VGC_MDB_D_DOUANE_OO" 
   (	"USERNAME_DOUANE" VARCHAR2(255 CHAR), 
	"ID" NUMBER, 
	"NAAM" VARCHAR2(255 CHAR), 
	"USERNAME" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table VGC_MDB_D_LAND_VAN_OORSPRONG
--------------------------------------------------------

  CREATE TABLE "VWASAS"."VGC_MDB_D_LAND_VAN_OORSPRONG" 
   (	"LND_ID" NUMBER(10,0), 
	"NAAM_LAND" VARCHAR2(70 CHAR), 
	"CODE_LAND" VARCHAR2(3 CHAR), 
	"EU_IND" VARCHAR2(1 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table VGC_XRELATIES
--------------------------------------------------------

  CREATE TABLE "VWASAS"."VGC_XRELATIES" 
   (	"ID" NUMBER(10,0), 
	"LND_ID" NUMBER(10,0), 
	"RLE_TYPE" VARCHAR2(5 CHAR), 
	"HUISNUMMER" VARCHAR2(10 CHAR), 
	"AANGEVERNUMMER" VARCHAR2(15 CHAR), 
	"NAAM" VARCHAR2(70 CHAR), 
	"ADRES" VARCHAR2(58 CHAR), 
	"PLAATS" VARCHAR2(35 CHAR), 
	"POSTCODE" VARCHAR2(9 CHAR), 
	"TELEFOONNUMMER" VARCHAR2(35 CHAR), 
	"FAXNUMMER" VARCHAR2(35 CHAR), 
	"OPMERKING" VARCHAR2(400 CHAR), 
	"EMAIL_ADRES" VARCHAR2(70 CHAR), 
	"SOORT_RELATIE" VARCHAR2(3 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
  GRANT DELETE ON "VWASAS"."VGC_XRELATIES" TO "METEOOR_WORK";
  GRANT INSERT ON "VWASAS"."VGC_XRELATIES" TO "METEOOR_WORK";
  GRANT SELECT ON "VWASAS"."VGC_XRELATIES" TO "METEOOR_WORK";
  GRANT UPDATE ON "VWASAS"."VGC_XRELATIES" TO "METEOOR_WORK";
--------------------------------------------------------
--  DDL for Table VGC_MDB_D_REDEN_AANHOUDING
--------------------------------------------------------

  CREATE TABLE "VWASAS"."VGC_MDB_D_REDEN_AANHOUDING" 
   (	"ID" NUMBER, 
	"REDEN_AANHOUDING" VARCHAR2(255 CHAR), 
	"ACTIEF" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table VGC_BESTEMMING
--------------------------------------------------------

  CREATE TABLE "VWASAS"."VGC_BESTEMMING" 
   (	"BESTEMMING_ID" NUMBER(10,0), 
	"BESTEMMING_CODE_DETAIL" VARCHAR2(10 CHAR), 
	"BESTEMMING_NAAM_DETAIL" VARCHAR2(70 CHAR), 
	"BESTEMMING_CODE" VARCHAR2(40 CHAR), 
	"BESTEMMING_NAAM" VARCHAR2(280 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
  GRANT DELETE ON "VWASAS"."VGC_BESTEMMING" TO "METEOOR_WORK";
  GRANT INSERT ON "VWASAS"."VGC_BESTEMMING" TO "METEOOR_WORK";
  GRANT SELECT ON "VWASAS"."VGC_BESTEMMING" TO "METEOOR_WORK";
  GRANT UPDATE ON "VWASAS"."VGC_BESTEMMING" TO "METEOOR_WORK";
--------------------------------------------------------
--  DDL for Table VGC_XKEURPUNTEN
--------------------------------------------------------

  CREATE TABLE "VWASAS"."VGC_XKEURPUNTEN" 
   (	"ID" NUMBER(10,0), 
	"NAAM" VARCHAR2(70 CHAR), 
	"ANIMO_CODE" VARCHAR2(14 CHAR), 
	"LND_ID" NUMBER(10,0), 
	"KPT_ID" NUMBER(10,0), 
	"KPT_TYPE" VARCHAR2(5 CHAR), 
	"LEVENDE_DIEREN_IND" VARCHAR2(1 CHAR), 
	"HC_TFR_IND" VARCHAR2(1 CHAR), 
	"HC_TCH_IND" VARCHAR2(1 CHAR), 
	"HC_NT_IND" VARCHAR2(1 CHAR), 
	"NHC_TFR_IND" VARCHAR2(1 CHAR), 
	"NHC_TCH_IND" VARCHAR2(1 CHAR), 
	"NHC_NT_IND" VARCHAR2(1 CHAR), 
	"LUCHTHAVEN_IND" VARCHAR2(1 CHAR), 
	"LANDCODE" VARCHAR2(3 CHAR), 
	"LANDNAAM" VARCHAR2(70 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
  GRANT DELETE ON "VWASAS"."VGC_XKEURPUNTEN" TO "METEOOR_WORK";
  GRANT INSERT ON "VWASAS"."VGC_XKEURPUNTEN" TO "METEOOR_WORK";
  GRANT SELECT ON "VWASAS"."VGC_XKEURPUNTEN" TO "METEOOR_WORK";
  GRANT UPDATE ON "VWASAS"."VGC_XKEURPUNTEN" TO "METEOOR_WORK";
--------------------------------------------------------
--  DDL for Table VGC_PARTIJ
--------------------------------------------------------

  CREATE TABLE "VWASAS"."VGC_PARTIJ" 
   (	"PTJ_ID" NUMBER(10,0), 
	"PARTIJ_TYPE" VARCHAR2(5 CHAR), 
	"GGS_NUMMER" VARCHAR2(10 CHAR), 
	"PARTIJ_STATUS" VARCHAR2(5 CHAR), 
	"LAND_VERZENDER" VARCHAR2(3 CHAR), 
	"ERKENNINGSNUMMER" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
  GRANT DELETE ON "VWASAS"."VGC_PARTIJ" TO "METEOOR_WORK";
  GRANT INSERT ON "VWASAS"."VGC_PARTIJ" TO "METEOOR_WORK";
  GRANT SELECT ON "VWASAS"."VGC_PARTIJ" TO "METEOOR_WORK";
  GRANT UPDATE ON "VWASAS"."VGC_PARTIJ" TO "METEOOR_WORK";
--------------------------------------------------------
--  DDL for Table VGC_MDB_F_ONAAN
--------------------------------------------------------

  CREATE TABLE "VWASAS"."VGC_MDB_F_ONAAN" 
   (	"ID_OMISSIE" NUMBER, 
	"GDB_NUMMER" NUMBER, 
	"ID_PROBLEEM" NUMBER, 
	"ID_PRODUCT_OA" NUMBER, 
	"ID_OPLOSSING" NUMBER, 
	"ID_LAND_VAN_OORSPRONG" NUMBER, 
	"ID_REDEN_AANHOUDING" NUMBER, 
	"GN_CODE" VARCHAR2(13 CHAR), 
	"ID_VETERIN_BESTEMMING" NUMBER(11,0), 
	"ID_AANVRAGER" NUMBER(11,0), 
	"USERNAME_DOUANE" VARCHAR2(255 CHAR), 
	"DATUM_OVERDRACHT" DATE, 
	"DATUM_BEHANDELING" DATE, 
	"NAAMGEEL" VARCHAR2(255 CHAR), 
	"OPMERKINGBLAUW" VARCHAR2(255 CHAR), 
	"DATUM_OPGEHEVEN" DATE, 
	"NAAMROOD" VARCHAR2(255 CHAR), 
	"OPMERKINGROOD" VARCHAR2(260 CHAR), 
	"GGS_NUMMER" VARCHAR2(10 CHAR), 
	"DATUM_AANKOMST" DATE, 
	"DATUM_ONDERTEKENING" DATE, 
	"PTJ_TYPE" VARCHAR2(5 CHAR), 
	"BIP" VARCHAR2(70 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table VGC_MDB_D_CATEGORIE
--------------------------------------------------------

  CREATE TABLE "VWASAS"."VGC_MDB_D_CATEGORIE" 
   (	"ID" NUMBER, 
	"TYPE" VARCHAR2(1 CHAR), 
	"FOUTCODE" VARCHAR2(2 CHAR), 
	"WEEGFACTOR" NUMBER, 
	"CATEGORIE" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table VGC_MDB_D_OPLOSSING
--------------------------------------------------------

  CREATE TABLE "VWASAS"."VGC_MDB_D_OPLOSSING" 
   (	"ID" NUMBER, 
	"OPLOSSING" VARCHAR2(255 CHAR), 
	"ACTIEF" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table VGC_MDB_D_GN_CODES
--------------------------------------------------------

  CREATE TABLE "VWASAS"."VGC_MDB_D_GN_CODES" 
   (	"GN_CODE_1" VARCHAR2(13 CHAR), 
	"GN_CODE_VADER_1" VARCHAR2(13 CHAR), 
	"GN_CODE_MEANING_1" VARCHAR2(4000 CHAR), 
	"GN_CODE_2" VARCHAR2(13 CHAR), 
	"GN_CODE_VADER_2" VARCHAR2(13 CHAR), 
	"GN_CODE_MEANING_2" VARCHAR2(4000 CHAR), 
	"GN_CODE_3" VARCHAR2(13 CHAR), 
	"GN_CODE_VADER_3" VARCHAR2(13 CHAR), 
	"GN_CODE_MEANING_3" VARCHAR2(4000 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table VGC_MDB_D_PRODUCT_OA
--------------------------------------------------------

  CREATE TABLE "VWASAS"."VGC_MDB_D_PRODUCT_OA" 
   (	"ID" NUMBER, 
	"PRODUCT" VARCHAR2(255 CHAR), 
	"ACTIEF" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table VGC_XVERVALLEN
--------------------------------------------------------

  CREATE TABLE "VWASAS"."VGC_XVERVALLEN" 
   (	"GGS_NUMMER" VARCHAR2(10 CHAR), 
	"REDEN_VERVALLEN" VARCHAR2(400 CHAR), 
	"DATUM_VERVALLEN" DATE, 
	"KENMERK_BRIEF_AANBIEDER" VARCHAR2(200 CHAR), 
	"MDR_ID_DAS" NUMBER(10,0), 
	"NAAM" VARCHAR2(70 CHAR), 
	"VOORNAAM" VARCHAR2(70 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
  GRANT DELETE ON "VWASAS"."VGC_XVERVALLEN" TO "METEOOR_WORK";
  GRANT INSERT ON "VWASAS"."VGC_XVERVALLEN" TO "METEOOR_WORK";
  GRANT SELECT ON "VWASAS"."VGC_XVERVALLEN" TO "METEOOR_WORK";
  GRANT UPDATE ON "VWASAS"."VGC_XVERVALLEN" TO "METEOOR_WORK";
--------------------------------------------------------
--  DDL for Table VGC_VOORAANVRAGEN
--------------------------------------------------------

  CREATE TABLE "VWASAS"."VGC_VOORAANVRAGEN" 
   (	"GGS_NUMMER" VARCHAR2(10 CHAR), 
	"PARTIJ_TYPE" VARCHAR2(5 CHAR), 
	"PARTIJ_STATUS" VARCHAR2(5 CHAR), 
	"LAND_VERZENDER" VARCHAR2(3 CHAR), 
	"RLE_ID" NUMBER(10,0), 
	"KPT_ID_AANGEB_BIP" NUMBER(10,0), 
	"KPT_ID_AANGEB_SIP" NUMBER(10,0), 
	"BESTEMMING_ID" NUMBER(10,0), 
	"PTJ_ID" NUMBER(10,0), 
	"ERKENNINGSNUMMER" NUMBER(10,0), 
	"BIP_NAAM" VARCHAR2(70 CHAR), 
	"KEURPUNT_NAAM" VARCHAR2(70 CHAR), 
	"AANGEVERNUMMER" VARCHAR2(15 CHAR), 
	"RELATIE_NAAM" VARCHAR2(70 CHAR), 
	"RELATIE_ID" NUMBER(10,0), 
	"BIP_ID" NUMBER(10,0), 
	"SIP_ID" NUMBER(10,0), 
	"BESTEMMING_CODE_DETAIL" VARCHAR2(10 CHAR), 
	"BESTEMMING_NAAM_DETAIL" VARCHAR2(70 CHAR), 
	"BESTEMMING_CODE" VARCHAR2(40 CHAR), 
	"BESTEMMING_NAAM" VARCHAR2(280 CHAR), 
	"M_VERPLICHT_IND" VARCHAR2(1 CHAR), 
	"LAB_OORDEEL" VARCHAR2(5 CHAR), 
	"REDEN_MONSTERNAME" VARCHAR2(5 CHAR), 
	"REDEN_MONSTERNAME_NAAM" VARCHAR2(240 CHAR), 
	"MONSTERNAME" NUMBER, 
	"POSITIEF_MONSTERNAME" NUMBER, 
	"BESLISSING_ID" NUMBER(10,0), 
	"BSE_ID" NUMBER(10,0), 
	"GBL_ID" NUMBER(10,0), 
	"BESLISSINGTYPE_ID" NUMBER(10,0), 
	"GEBRUIKSDOEL_ID" NUMBER(10,0), 
	"ARTIKEL_8_IND" VARCHAR2(1 CHAR), 
	"WETTELIJKE_BASIS" VARCHAR2(5 CHAR), 
	"DEFINITIEF_IND" VARCHAR2(1 CHAR), 
	"CREATION_DATE" NUMBER, 
	"BESLISSINGTYPE_CODE" VARCHAR2(10 CHAR), 
	"BESLISSINGTYPE_NAAM" VARCHAR2(70 CHAR), 
	"GEBRUIKSDOEL_NAAM" VARCHAR2(70 CHAR), 
	"WETTELIJKE_BASIS_NAAM" VARCHAR2(240 CHAR), 
	"GEWICHT_NETTO" NUMBER, 
	"GEWICHT_BRUTO" NUMBER, 
	"PROD_AANTAL" NUMBER, 
	"AANTAL" NUMBER, 
	"COLLI_ID" NUMBER(10,0), 
	"PRODUCT_ID" NUMBER(10,0), 
	"DATE_GEWICHT" DATE, 
	"PRODUCT_AARD" VARCHAR2(100 CHAR), 
	"PRODUCT_CODE" VARCHAR2(14 CHAR), 
	"VOORNEMEN_TOT_WEIGEREN" NUMBER, 
	"ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
  GRANT DELETE ON "VWASAS"."VGC_VOORAANVRAGEN" TO "METEOOR_WORK";
  GRANT INSERT ON "VWASAS"."VGC_VOORAANVRAGEN" TO "METEOOR_WORK";
  GRANT SELECT ON "VWASAS"."VGC_VOORAANVRAGEN" TO "METEOOR_WORK";
  GRANT UPDATE ON "VWASAS"."VGC_VOORAANVRAGEN" TO "METEOOR_WORK";
--------------------------------------------------------
--  Constraints for Table VGC_MDB_D_AANVRAGER
--------------------------------------------------------

  ALTER TABLE "VWASAS"."VGC_MDB_D_AANVRAGER" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VGC_MDB_D_LAND_VAN_OORSPRONG
--------------------------------------------------------

  ALTER TABLE "VWASAS"."VGC_MDB_D_LAND_VAN_OORSPRONG" MODIFY ("LND_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VGC_MDB_D_GN_CODES
--------------------------------------------------------

  ALTER TABLE "VWASAS"."VGC_MDB_D_GN_CODES" MODIFY ("GN_CODE_1" NOT NULL ENABLE);
