--------------------------------------------------------
--  DDL for Table DBC_MONITORING
--------------------------------------------------------

  CREATE TABLE "VWASAS"."DBC_MONITORING" 
   (	"OMSCHRIJVING" VARCHAR2(50 CHAR), 
	"JAAR" NUMBER, 
	"AANTAL_RECORDS" NUMBER, 
	"UREN" NUMBER, 
	"NETTO_UREN" NUMBER, 
	"REISUREN_EXPLICIET" NUMBER, 
	"REAL_KOSTPRIJS" NUMBER, 
	"PHRT_URENPRIORITEIT" NUMBER, 
	"PLAN_KOSTPRIJS" NUMBER, 
	"PROGNOSE" NUMBER, 
	"PHRT_URENPRIORITEIT_YTD" NUMBER, 
	"PLAN_KOSTPRIJS_YTD" NUMBER, 
	"PROGNOSE_YTD" NUMBER, 
	"KWARTIEREN" NUMBER, 
	"AANTAL_EENHEDEN" NUMBER, 
	"FACTUURBEDRAG" NUMBER, 
	"VERWACHTE_UREN" NUMBER, 
	"ARBEIDSDUUR_UREN" NUMBER, 
	"FORMELE_UREN" NUMBER, 
	"CONCEPT_UREN" NUMBER, 
	"CONCEPT_NETTO_UREN" NUMBER, 
	"CONCEPT_REISTIJD" NUMBER, 
	"NETTO_FDC" NUMBER, 
	"INFORMEEL_VERLOF_VERZUIM" NUMBER, 
	"TOEGEKEND_VERLOF" NUMBER, 
	"DAG_UREN" NUMBER, 
	"DAGEN_GESCHREVEN" NUMBER, 
	"VERWACHTE_DAG" NUMBER, 
	"GEWERKTE_DAG" NUMBER, 
	"MISSENDE_DAG" NUMBER, 
	"ZIEKTE_UREN" NUMBER, 
	"AANTAL" NUMBER, 
	"AANTAL_A" NUMBER, 
	"AANTAL_NA" NUMBER, 
	"AANTAL_NVT" NUMBER, 
	"AANTAL_OV" NUMBER, 
	"AANTAL_GEPLANDE_INSPECTIES" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table DBC_VERVERSINGS_DATA
--------------------------------------------------------

  CREATE TABLE "VWASAS"."DBC_VERVERSINGS_DATA" 
   (	"BRON" VARCHAR2(10 CHAR), 
	"JAAR" NUMBER, 
	"VERVERSINGSDATUM" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
  GRANT DELETE ON "VWASAS"."DBC_VERVERSINGS_DATA" TO "METEOOR_WORK";
  GRANT INSERT ON "VWASAS"."DBC_VERVERSINGS_DATA" TO "METEOOR_WORK";
  GRANT SELECT ON "VWASAS"."DBC_VERVERSINGS_DATA" TO "METEOOR_WORK";
  GRANT UPDATE ON "VWASAS"."DBC_VERVERSINGS_DATA" TO "METEOOR_WORK";
--------------------------------------------------------
--  DDL for Table DBC_REF_TABEL02_EGB_JAARBEDRAG
--------------------------------------------------------

  CREATE TABLE "VWASAS"."DBC_REF_TABEL02_EGB_JAARBEDRAG" 
   (	"JAAR" NUMBER(5,0), 
	"BEDRAG" NUMBER(11,2), 
	"HHD_ID_FICTIEF" NUMBER(11,0), 
	"DOMEIN" VARCHAR2(80 CHAR), 
	"WERKPAKKET" VARCHAR2(80 CHAR), 
	"DOELSTELLING" VARCHAR2(80 CHAR), 
	"RETRIBUTIE_CATEGORIE" VARCHAR2(80 CHAR), 
	"CODE_WERKPAKKET" VARCHAR2(2 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table DBC_REF_TABEL06_PRAC_BRUT_WPPR
--------------------------------------------------------

  CREATE TABLE "VWASAS"."DBC_REF_TABEL06_PRAC_BRUT_WPPR" 
   (	"WPPR_CODE" VARCHAR2(4 CHAR), 
	"PRACT_FACTOR" NUMBER(6,2), 
	"BRON" VARCHAR2(20 CHAR), 
	"BEGINDATUM" DATE, 
	"EINDDATUM" DATE, 
	"WP_CODE" VARCHAR2(2 CHAR), 
	"PR_CODE" VARCHAR2(2 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table DBC_VERVERSINGS_DATA_BU
--------------------------------------------------------

  CREATE TABLE "VWASAS"."DBC_VERVERSINGS_DATA_BU" 
   (	"BRON" VARCHAR2(10 CHAR), 
	"JAAR" NUMBER, 
	"VERVERSINGSDATUM" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table DBC_REF_TABEL03_FACT_HERVERDEL
--------------------------------------------------------

  CREATE TABLE "VWASAS"."DBC_REF_TABEL03_FACT_HERVERDEL" 
   (	"DOMEIN" VARCHAR2(80 CHAR), 
	"WERKPAKKET" VARCHAR2(80 CHAR), 
	"PERCENTAGE" NUMBER(6,2), 
	"JAAR" NUMBER(5,0), 
	"DOELSTELLING" VARCHAR2(80 CHAR), 
	"HHD_ID" NUMBER(11,0), 
	"HHD_ID_FICTIEF" NUMBER(11,0), 
	"RETRIBUTIE_CATEGORIE" VARCHAR2(80 CHAR), 
	"CODE_WERKPAKKET" VARCHAR2(2 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table DBC_REF_B_DBC_IST_PDT_SPN
--------------------------------------------------------

  CREATE TABLE "VWASAS"."DBC_REF_B_DBC_IST_PDT_SPN" 
   (	"LOAD_DTS" DATE, 
	"ID" NUMBER(12,0), 
	"THEMA" VARCHAR2(240 CHAR), 
	"SPIN_TAAKNAAM" VARCHAR2(240 CHAR), 
	"INSPECT_PRODUCT_TYPE" VARCHAR2(240 CHAR), 
	"BEGINDATUM" DATE, 
	"EINDDATUM" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table DBC_REF_TABEL04_KCDV_DERDEN
--------------------------------------------------------

  CREATE TABLE "VWASAS"."DBC_REF_TABEL04_KCDV_DERDEN" 
   (	"DOELCODE" VARCHAR2(4 CHAR), 
	"AFGELEIDE_DOELSTELLING" VARCHAR2(80 CHAR), 
	"FACT_KWARTIER_IND" VARCHAR2(1 CHAR), 
	"PRODUCTCODE" VARCHAR2(2 CHAR), 
	"PRODUCT" VARCHAR2(80 CHAR), 
	"ARTIKELCODE" VARCHAR2(2 CHAR), 
	"ARTIKEL" VARCHAR2(80 CHAR), 
	"HHD_ID" NUMBER(11,0), 
	"TARIEF" NUMBER(9,2), 
	"JAAR" NUMBER(5,0), 
	"BEGINDATUM" DATE, 
	"EINDDATUM" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table DBC_REF_KOSTPRIJS
--------------------------------------------------------

  CREATE TABLE "VWASAS"."DBC_REF_KOSTPRIJS" 
   (	"KOSTPRIJS_BEGIN" DATE, 
	"KOSTPRIJS_EINDE" DATE, 
	"PRODUCT_CODE" VARCHAR2(13 CHAR), 
	"PRODUCT_NAAM" VARCHAR2(35 CHAR), 
	"KOSTPRIJS_BEDRAG" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table DBC_MONITORING_DIM
--------------------------------------------------------

  CREATE TABLE "VWASAS"."DBC_MONITORING_DIM" 
   (	"TABEL" VARCHAR2(200 CHAR), 
	"KOLOM" VARCHAR2(200 CHAR), 
	"WAARDE_CHAR" VARCHAR2(200 CHAR), 
	"WAARDE_NUM" NUMBER, 
	"WAARDE_DATUM" DATE, 
	"AANTAL" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table DBC_MONITORING_TRANSPOSE
--------------------------------------------------------

  CREATE TABLE "VWASAS"."DBC_MONITORING_TRANSPOSE" 
   (	"JAAR" NUMBER, 
	"OMSCHRIJVING" VARCHAR2(26 CHAR), 
	"F_JAARPLAN" NUMBER, 
	"BU_F_JAARPLAN" NUMBER, 
	"F_QTQ_GEPLANDE_INSPECTIES" NUMBER, 
	"BU_F_QTQ_GEPLANDE_INSPECTIES" NUMBER, 
	"F_REALDOELTAAK" NUMBER, 
	"BU_F_REALDOELTAAK" NUMBER, 
	"F_UITGEVOERDE_INSPECTIE" NUMBER, 
	"BU_F_UITGEVOERDE_INSPECTIE" NUMBER, 
	"FACT_F_FACTUUREENHEDEN" NUMBER, 
	"BU_FACT_F_FACTUUREENHEDEN" NUMBER, 
	"FACT_F_JAARPLAN" NUMBER, 
	"BU_FACT_F_JAARPLAN" NUMBER, 
	"FACT_F_REALDOELTAAK" NUMBER, 
	"BU_FACT_F_REALDOELTAAK" NUMBER, 
	"UR_F_DAGEN_VERWACHT_GEWERKT" NUMBER, 
	"BU_UR_F_DAGEN_VERWACHT_GEWERKT" NUMBER, 
	"UR_F_DAGENVERANTW" NUMBER, 
	"BU_UR_F_DAGENVERANTW" NUMBER, 
	"UR_F_FORMEEL" NUMBER, 
	"BU_UR_F_FORMEEL" NUMBER, 
	"UR_F_VERLOF" NUMBER, 
	"BU_UR_F_VERLOF" NUMBER, 
	"UR_F_VERWACHT" NUMBER, 
	"BU_UR_F_VERWACHT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table DBC_MONITORING_DIM_MISSEND
--------------------------------------------------------

  CREATE TABLE "VWASAS"."DBC_MONITORING_DIM_MISSEND" 
   (	"DIMENSIETABEL" VARCHAR2(200 CHAR), 
	"FEITENTABEL" VARCHAR2(200 CHAR), 
	"KOLOM" VARCHAR2(200 CHAR), 
	"WAARDE_CHAR" VARCHAR2(200 CHAR), 
	"WAARDE_NUM" NUMBER(14,0), 
	"WAARDE_DATUM" DATE, 
	"AANTAL" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table DBC_REF_B_MCSPLUS_IJKMOMENTEN
--------------------------------------------------------

  CREATE TABLE "VWASAS"."DBC_REF_B_MCSPLUS_IJKMOMENTEN" 
   (	"LOAD_DTS" DATE, 
	"ID" NUMBER(12,0), 
	"THEMA" VARCHAR2(240 CHAR), 
	"GEPLANDE_BEREKENINGSDATUM" DATE, 
	"PLANNINGSJAAR" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table DBC_REF_TABEL05_SPIN_FAFAK_COD
--------------------------------------------------------

  CREATE TABLE "VWASAS"."DBC_REF_TABEL05_SPIN_FAFAK_COD" 
   (	"SPN_CODE_DOELSTELLING" VARCHAR2(4 CHAR), 
	"DOELSTELLING_NAAM" VARCHAR2(80 CHAR), 
	"DOMEIN" VARCHAR2(255 CHAR), 
	"FFK_PRODUCTCODE" VARCHAR2(2 CHAR), 
	"FFK_ARTIKELCODE" VARCHAR2(2 CHAR), 
	"FACT_KWARTIER_IND" VARCHAR2(1 CHAR), 
	"BEGINDATUM" DATE, 
	"EINDDATUM" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table DBC_REF_TABEL01_RETRIBUTIE_CAT
--------------------------------------------------------

  CREATE TABLE "VWASAS"."DBC_REF_TABEL01_RETRIBUTIE_CAT" 
   (	"RETRIBUTIE_CATEGORIE" VARCHAR2(2000 CHAR), 
	"DOMEIN" VARCHAR2(255 CHAR), 
	"HANDHAVINGSDOELSTELLING" VARCHAR2(80 CHAR), 
	"ID" NUMBER(11,0), 
	"OPDRACHTGEVER" VARCHAR2(80 CHAR), 
	"JAAR" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
--------------------------------------------------------
--  Constraints for Table DBC_REF_TABEL05_SPIN_FAFAK_COD
--------------------------------------------------------

  ALTER TABLE "VWASAS"."DBC_REF_TABEL05_SPIN_FAFAK_COD" MODIFY ("DOMEIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DBC_REF_TABEL01_RETRIBUTIE_CAT
--------------------------------------------------------

  ALTER TABLE "VWASAS"."DBC_REF_TABEL01_RETRIBUTIE_CAT" MODIFY ("DOMEIN" NOT NULL ENABLE);
  ALTER TABLE "VWASAS"."DBC_REF_TABEL01_RETRIBUTIE_CAT" MODIFY ("HANDHAVINGSDOELSTELLING" NOT NULL ENABLE);
  ALTER TABLE "VWASAS"."DBC_REF_TABEL01_RETRIBUTIE_CAT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "VWASAS"."DBC_REF_TABEL01_RETRIBUTIE_CAT" MODIFY ("OPDRACHTGEVER" NOT NULL ENABLE);
