--------------------------------------------------------
--  DDL for Table REF_OBIEE_AUTORISATIE
--------------------------------------------------------

  CREATE TABLE "VWASAS"."REF_OBIEE_AUTORISATIE" 
   (	"BEGINDATUM" DATE, 
	"EINDDATUM" DATE DEFAULT TO_DATE('31-12-4712', 'dd-mm-yyyy'), 
	"WINDOWS_USERNAME" VARCHAR2(40 CHAR), 
	"SAP_NUMMER" NUMBER, 
	"PDIRECT" VARCHAR2(5 CHAR), 
	"NAAM_MEDEWERKER" VARCHAR2(50 CHAR), 
	"ACHTERNAAM" VARCHAR2(30 CHAR), 
	"FP_NAAM" VARCHAR2(40 CHAR), 
	"LEIDINGGEVEND" VARCHAR2(20 CHAR), 
	"KP_TEAM" VARCHAR2(6 CHAR), 
	"TEAM_NAAM" VARCHAR2(40 CHAR), 
	"KP_AFDELING" VARCHAR2(6 CHAR), 
	"AFDELING" VARCHAR2(50 CHAR), 
	"KP_DIVISIE" VARCHAR2(6 CHAR), 
	"DIVISIE" VARCHAR2(50 CHAR), 
	"KP_DIRECTIE" VARCHAR2(6 CHAR), 
	"DIRECTIE" VARCHAR2(80 CHAR), 
	"KP_CONCERN" VARCHAR2(6 CHAR), 
	"ORGANISATIE" VARCHAR2(50 CHAR), 
	"R_PERSOONLIJK" NUMBER, 
	"R_PERSOONLIJK_STRIKT" NUMBER, 
	"R_DIERPROEF" NUMBER, 
	"DEFAULT_DB" VARCHAR2(40 CHAR), 
	"BIBEHEER" NUMBER, 
	"BIONTWIKKEL" NUMBER, 
	"BICONSUMERS" NUMBER, 
	"DB_CENTRAAL" NUMBER, 
	"DB_CENTRAAL_DENY" NUMBER, 
	"DB_PROCES" NUMBER, 
	"DB_EFFECT" NUMBER, 
	"DB_INSPECTIEHISTORIE" NUMBER, 
	"DB_VGC" NUMBER, 
	"DB_VGCMAN" NUMBER, 
	"DB_CONTROL" NUMBER, 
	"DIV_CV" NUMBER, 
	"DIV_VI" NUMBER, 
	"DIV_KCDV" NUMBER, 
	"DIV_CV_ONTW" NUMBER, 
	"DIV_VI_ONTW" NUMBER, 
	"DIV_KCDV_ONTW" NUMBER, 
	"DB_PR_FINDB" NUMBER, 
	"DB_EBS" NUMBER, 
	"R_PERSOONLIJK_KPN" VARCHAR2(6 CHAR), 
	"SAP_NUMMER_CHAR" VARCHAR2(8 CHAR), 
	"R_AGRESSIE_STRIKT" NUMBER, 
	"UITZONDERING_DTV" VARCHAR2(80 CHAR), 
	"UITZONDERING_DBC" VARCHAR2(80 CHAR), 
	"TOUCH" VARCHAR2(200 CHAR) DEFAULT SYS_CONTEXT ('USERENV', 'OS_USER')||' - '|| SYS_CONTEXT ('USERENV', 'HOST')||' - '||SYS_CONTEXT ('USERENV', 'MODULE')||' - '|| to_char(sysdate, 'YYYYMMDD HH24:mi'), 
	"ID" NUMBER, 
	"IND_HUIDIG_RECORD" NUMBER(1,0) DEFAULT 1, 
	"INGANGSDATUM_RECORD" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table REF_OBIEE_AUTO_EXTRA_109
--------------------------------------------------------

  CREATE TABLE "VWASAS"."REF_OBIEE_AUTO_EXTRA_109" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"BEGINDATUM" DATE, 
	"EINDDATUM" DATE DEFAULT TO_DATE('31-12-4712', 'dd-mm-yyyy'), 
	"IND_HUIDIG_RECORD" NUMBER(1,0) DEFAULT '1', 
	"MEDEWERKER" VARCHAR2(40 CHAR), 
	"ORGANISATIE_NIVEAU" VARCHAR2(100 CHAR), 
	"KOSTENPLAATS" VARCHAR2(6 CHAR), 
	"TOUCH" VARCHAR2(200 CHAR) DEFAULT SYS_CONTEXT ('USERENV', 'OS_USER')||' - '|| SYS_CONTEXT ('USERENV', 'HOST')||' - '||SYS_CONTEXT ('USERENV', 'MODULE')||' - '|| to_char(sysdate, 'YYYYMMDD HH24:mi')
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table REF_OBIEE_AUTORISATIE_EXTRA
--------------------------------------------------------

  CREATE TABLE "VWASAS"."REF_OBIEE_AUTORISATIE_EXTRA" 
   (	"BEGINDATUM" DATE, 
	"EINDDATUM" DATE DEFAULT TO_DATE('31-12-4712', 'dd-mm-yyyy'), 
	"MEDEWERKER" VARCHAR2(40 CHAR), 
	"ORGANISATIE_NIVEAU" VARCHAR2(100 CHAR), 
	"KOSTENPLAATS" VARCHAR2(6 CHAR), 
	"IND_HUIDIG_RECORD" NUMBER(1,0) DEFAULT 1, 
	"ID" NUMBER, 
	"TOUCH" VARCHAR2(200 CHAR) DEFAULT SYS_CONTEXT ('USERENV', 'OS_USER')||' - '|| SYS_CONTEXT ('USERENV', 'HOST')||' - '||SYS_CONTEXT ('USERENV', 'MODULE')||' - '|| to_char(sysdate, 'YYYYMMDD HH24:mi')
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
--------------------------------------------------------
--  DDL for Table REF_OBIEE_AUTORISATIE_WLS
--------------------------------------------------------

  CREATE TABLE "VWASAS"."REF_OBIEE_AUTORISATIE_WLS" 
   (	"WINDOWS_USERNAME" VARCHAR2(40 CHAR), 
	"NAAM_MEDEWERKER" VARCHAR2(40 CHAR), 
	"ROLES" VARCHAR2(40 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MI_DATA"   NO INMEMORY ;
--------------------------------------------------------
--  Constraints for Table REF_OBIEE_AUTORISATIE
--------------------------------------------------------

  ALTER TABLE "VWASAS"."REF_OBIEE_AUTORISATIE" MODIFY ("BEGINDATUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table REF_OBIEE_AUTO_EXTRA_109
--------------------------------------------------------

  ALTER TABLE "VWASAS"."REF_OBIEE_AUTO_EXTRA_109" MODIFY ("ID" NOT NULL ENABLE);
