WITH meta AS (                                                                                                                                                                                             
    SELECT                                                                                                                                                                                                          
        dl.dl_id,                                                                                                                                                                                                   
        dl.dl_naam,                                                                                                                                                                                                           
        dl.dl_frequentie_info,                                                                                                                                                                                                       
        td.type_dl_naam,                                                                                                                                                                                               
        'OKV_'                                                                                                                                                                                                      
        || upper(br.bron_naam)                                                                                                                                                                                                 
        || '_PO'            okv_schema,                                                                                                                                                                                                          
        'OKV_'                                                                                                                                                                                                      
        || upper(t.tabel_naam)                                                                                                                                                                                                    
        || '_HV'            tabel,                                                                                                                                                                                                          
        t.tabel_leverwijze,                                                                                                                                                                                              
        upper(k.kolom_naam) kolom,                                                                                                                                                                                                      
        m.maskeer_beleid_id,                                                                                                                                                                                                       
        m.maskeer_beleid_naam,                                                                                                                                                                                               
        k.kolom_id,                                                                                                                                                                                                           
        k.admin_tijdslijn_ind,                                                                                                                                                                                                        
        k.kolom_positie,                                                                                                                                                                                                  
        k.kolom_naam,                                                                                                                                                                                                    
        k.kolom_datatype,                                                                                                                                                                                             
        k.kolom_lengte,                                                                                                                                                                                                   
        k.kolom_ind_verplicht,                                                                                                                                                                                                     
        k.kolom_ind_status,                                                                                                                                                                                                          
        k.kolom_sql_afgeleide,                                                                                                                                                                                                     
        k.kolom_ind_identificerend,                                                                                                                                                                                                          
        t.tabel_id                                                                                                                                                                                                
    FROM                                                                                                                                                                                                           
             dim_metadata.dl_datalevering_tb dl                                                                                                                                                                                                    
        INNER JOIN dim_metadata.dl_bron_tb              br ON ( dl.bron_id = br.bron_id )                                                                                                                                                                    
        INNER JOIN dim_metadata.dl_tabel_tb             t ON ( t.dl_id = dl.dl_id )                                                                                                                                                                                       
        INNER JOIN dim_metadata.dl_kolom_tb             k ON ( t.tabel_id = k.tabel_id )                                                                                                                                                                        
        INNER JOIN dim_metadata.dl_maskeer_beleid_tb    m ON ( k.maskeer_beleid_id = m.maskeer_beleid_id )                                                                                                               
        INNER JOIN dim_metadata.dl_type_datalevering_tb td ON ( dl.type_dl_id = td.type_dl_id )                                                                                                                                              
    WHERE                                                                                                                                                                                                         
        k.kolom_ind_brz_overslaan <> 'J'                                                                                                                                                                                                
    GROUP BY                                                                                                                                                                                                   
        dl.dl_id,                                                                                                                                                                                                   
        dl.dl_naam,                                                                                                                                                                                                           
        dl.dl_frequentie_info,                                                                                                                                                                                                       
        td.type_dl_naam,                                                                                                                                                                                               
        br.bron_naam,                                                                                                                                                                                                     
        t.tabel_naam,                                                                                                                                                                                                       
        t.tabel_leverwijze,                                                                                                                                                                                              
        k.kolom_naam,                                                                                                                                                                                                    
        m.maskeer_beleid_id,                                                                                                                                                                                                       
        m.maskeer_beleid_naam,                                                                                                                                                                                               
        k.kolom_id,                                                                                                                                                                                                           
        k.admin_tijdslijn_ind,                                                                                                                                                                                                        
        k.kolom_positie,                                                                                                                                                                                                  
        k.kolom_naam,                                                                                                                                                                                                    
        k.kolom_datatype,                                                                                                                                                                                             
        k.kolom_lengte,                                                                                                                                                                                                   
        k.kolom_ind_verplicht,                                                                                                                                                                                                     
        k.kolom_ind_status,                                                                                                                                                                                                          
        k.kolom_sql_afgeleide,                                                                                                                                                                                                     
        k.kolom_ind_identificerend,                                                                                                                                                                                                          
        t.tabel_id                                                                                                                                                                                                
), proces_run AS (                                                                                                                                                                                                         
    SELECT                                                                                                                                                                                                          
        proces.dl_run_id,                                                                                                                                                                                                
        run.dl_id,                                                                                                                                                                                                
        proces.proces_naam,                                                                                                                                                                                                        
        proces.proces_status,                                                                                                                                                                                                       
        CASE                                                                                                                                                                                                         
            WHEN proces.proces_status = 'Klaar'      THEN                                                                                                                                                                                                   
                MAX(proces.log_tijdstip)                                                                                                                                                                                                       
            WHEN proces.proces_status = 'Afgebroken' THEN                                                                                                                                                                                                           
                MAX(proces.log_tijdstip)                                                                                                                                                                                                       
            WHEN proces.proces_status = ( 'Lopend' ) THEN                                                                                                                                                                                              
                MIN(proces.log_tijdstip)                                                                                                                                                                                                        
        END AS tijdstip                                                                                                                                                                                                     
    FROM                                                                                                                                                                                                           
             dim_logging.dl_proces_log_tb proces                                                                                                                                                                                                  
        INNER JOIN dim_logging.dl_run_log_tb run ON ( proces.dl_run_id = run.dl_run_id )                                                                                                                                                            
    GROUP BY                                                                                                                                                                                                   
        proces.dl_run_id,                                                                                                                                                                                                
        run.dl_id,                                                                                                                                                                                                
        proces.proces_naam,                                                                                                                                                                                                        
        proces.proces_status                                                                                                                                                                                                        
    ORDER BY                                                                                                                                                                                                    
        dl_run_id DESC,                                                                                                                                                                                                   
        tijdstip DESC                                                                                                                                                                                                          
), status AS (                                                                                                                                                                                                    
    SELECT DISTINCT                                                                                                                                                                                                      
        dl_run_id,                                                                                                                                                                                               
        dl_id,                                                                                                                                                                                                        
        proces_naam,                                                                                                                                                                                                       
        proces_status,                                                                                                                                                                                                      
        CASE                                                                                                                                                                                                         
            WHEN proces_status = 'Afgebroken' THEN 1                                                                                                                                                                                                                     
            ELSE 0                                                                                                                                                                                                                                                                                                                 
       END AS run_fout_indicatie                                                                                                                                                                                              
    FROM                                                                                                                                                                                                           
        proces_run                                                                                                                                                                                                            
    WHERE                                                                                                                                                                                                         
        proces_status = 'Klaar'                                                                                                                                                                                                       
        OR proces_status = 'Afgebroken'                                                                                                                                                                                                 
), runstatus AS (                                                                                                                                                                                                            
    SELECT                                                                                                                                                                                                          
        dl_run_id,                                                                                                                                                                                               
        SUM(run_fout_indicatie) AS aantal                                                                                                                                                                                             
    FROM                                                                                                                                                                                                           
        status                                                                                                                                                                                                       
    GROUP BY                                                                                                                                                                                                   
        dl_run_id                                                                                                                                                                                                
), query AS (                                                                                                                                                                                                    
    SELECT DISTINCT                                                                                                                                                                                                      
        run.dl_id,                                                                                                                                                                                                
        proces.dl_run_id,                                                                                                                                                                                                
        CASE                                                                                                                                                                                                         
            WHEN runstatus.aantal = 0 THEN                                                                                                                                                                                                            
                'OK'                                                                                                                                                                                                   
            ELSE                                                                                                                                                                                                      
                'NOK'                                                                                                                                                                                               
        END AS run_status                                                                                                                                                                                              
    FROM                                                                                                                                                                                                           
             dim_logging.dl_proces_log_tb proces                                                                                                                                                                                                  
        INNER JOIN dim_logging.dl_run_log_tb run ON ( proces.dl_run_id = run.dl_run_id )                                                                                                                                                            
        INNER JOIN runstatus ON ( proces.dl_run_id = runstatus.dl_run_id )                                                                                                                                                                                           
), aantal AS (                                                                                                                                                                                                   
    SELECT                                                                                                                                                                                                          
        dl_id,                                                                                                                                                                                                        
        COUNT(*) AS aantal                                                                                                                                                                                                           
    FROM                                                                                                                                                                                                           
        query                                                                                                                                                                                                        
    GROUP BY                                                                                                                                                                                                   
        dl_id                                                                                                                                                                                                          
), aantal_goed_fout_tmp AS (                                                                                                                                                                                                 
    SELECT                                                                                                                                                                                                          
        dl_id,                                                                                                                                                                                                        
        run_status,                                                                                                                                                                                             
        COUNT(*) AS aantal                                                                                                                                                                                                           
    FROM                                                                                                                                                                                                           
        query                                                                                                                                                                                                        
    GROUP BY                                                                                                                                                                                                   
        dl_id,                                                                                                                                                                                                        
        run_status                                                                                                                                                                                              
), aantal_goed_fout AS (                                                                                                                                                                                                            
    SELECT                                                                                                                                                                                                          
        a.dl_id,                                                                                                                                                                                                     
        nvl(MAX(b.aantal),                                                                                                                                                                                             
            0) AS goed,                                                                                                                                                                                                        
        nvl(MAX(c.aantal),                                                                                                                                                                                             
            0) AS fout                                                                                                                                                                                                           
    FROM                                                                                                                                                                                                           
        aantal_goed_fout_tmp a                                                                                                                                                                                                  
        LEFT JOIN aantal_goed_fout_tmp b ON a.dl_id = b.dl_id                                                                                                                                                                                                    
                                            AND b.run_status = 'OK'                                                                                                                                                                                          
        LEFT JOIN aantal_goed_fout_tmp c ON a.dl_id = c.dl_id                                                                                                                                                                     
                                            AND c.run_status = 'NOK'                                                                                                                                                                                                       
    GROUP BY                                                                                                                                                                                                   
        a.dl_id                                                                                                                                                                                                      
)                                                                                                                                                                                                           
SELECT                                                                                                                                                                                               
    meta.okv_schema,                                                                                                   
    meta.dl_naam,                                                                                                                           
    meta.dl_frequentie_info,                                                                                                                                                                                     
    meta.type_dl_naam,                                                                                                               
    aantal.aantal                                                          AS aantal_runs_per_bron,                                                                                                         
    aantal_goed_fout.goed                                                  AS aantal_runs_goed,                                                                                                                     
    aantal_goed_fout.fout                                                  AS aantal_runs_fout,                                                                                                         
    proces_run.dl_run_id,                                                                                                             
    runstatus.aantal                                                       AS run_fout,                                                                                                                
    proces_run.dl_id,                                                                                                                      
    proces_run.proces_naam,                                                                                                                    
    status.proces_status,                                                                                              
    min(proces_run.tijdstip)                                               START_TIJD,                                                                                                                           
    MAX(proces_run.tijdstip)                                               eind_TIJD,                                                                                                                                                                                                           
    round((MAX(proces_run.tijdstip) - MIN(proces_run.tijdstip)) * 60 * 24) AS verschil                                                                                                                                                                   
FROM                                                                                                                                                                                                
         proces_run                                                                                                                                                                                                           
    INNER JOIN meta ON ( proces_run.dl_id = meta.dl_id )                                                                                                                                                                                                           
    INNER JOIN aantal ON ( proces_run.dl_id = aantal.dl_id )                                                                                                                                                                                                       
    INNER JOIN status ON ( proces_run.dl_run_id = status.dl_run_id )                                                                                                                                                                                                    
                         AND ( proces_run.proces_naam = status.proces_naam )                                                                                                                                                                                               
    INNER JOIN runstatus ON ( proces_run.dl_run_id = runstatus.dl_run_id )                                                                                                                                                                                      
    INNER JOIN aantal_goed_fout ON ( proces_run.dl_id = aantal_goed_fout.dl_id )                                                                                                                                                                       
GROUP BY                                                                                                                                                                                                        
    proces_run.dl_run_id,                                                                                                                                                                                                           
    runstatus.aantal,                                                                                                                                                                                                     
    proces_run.dl_id,                                                                                                                                                                                                     
    proces_run.proces_naam,                                                                                                                                                                                                   
    meta.dl_naam,                                                                                                                                                                                                         
    meta.dl_frequentie_info,                                                                                                                                                                                                     
    meta.type_dl_naam,                                                                                                                                                                                              
    meta.okv_schema,                                                                                                                                                                                                  
    aantal.aantal,                                                                                                                                                                                                            
    aantal_goed_fout.goed,                                                                                                                                                                                                       
    aantal_goed_fout.fout,                                                                                                                                                                                                         
    status.proces_status                                                                                                                                                                                              
ORDER BY                                                                                                                                                                                                        
    proces_run.dl_run_id DESC;